# Generated by data-raw/generate_linters.R -- do not edit by hand.
# Source: pkgaudit rules database version 0.1.0
# Generated: 2026-06-27T14:45:46

#' All lintrsecurity linters
#'
#' Returns all stable lintrsecurity linters as a named list suitable for
#' passing to \code{lintr::lint()} or \code{lintr::lint_package()}.
#'
#' @return A named list of linter objects.
#'
#' @examples
#' \dontrun{
#' lintr::lint_package(
#'   linters = c(
#'     lintr::linters_with_defaults(),
#'     lintrsecurity::lintrsecurity_linters()
#'   )
#' )
#' }
#'
#' @export
lintrsecurity_linters <- function() {
  list(
    onload_calls_httr_POST_linter = onload_calls_httr_POST_linter(),
    onload_calls_system_linter = onload_calls_system_linter()
  )
}
