# Generated by data-raw/generate_linters.R -- do not edit by hand.
# Source: pkgaudit rules database version 0.1.0
# Generated: 2026-06-27T14:45:46

#' Flag system() or system2() calls inside .onLoad or .onAttach.
#'
#' @details
#' **Lint message:** system() or system2() inside .onLoad or .onAttach hooks execute
#'   arbitrary shell commands automatically when a package is loaded.
#'
#' **Severity:** `warning`
#'
#' **MITRE ATT\&CK:** [T1059.004](https://attack.mitre.org/techniques/T1059/004/), [T1195.002](https://attack.mitre.org/techniques/T1195/002/)
#'
#' For full documentation of the targeted vulnerability, see the [pkgaudit documentation](https://tylerjssmith.github.io/pkgaudit).
#'
#' @return A linter function of class \code{linter}.
#'
#' @examples
#' \dontrun{
#' lintr::lint(
#'   text    = ".onLoad <- function(l, p) { system(\"id\") }",
#'   linters = onload_calls_system_linter()
#' )
#' }
#'
#' @export
onload_calls_system_linter <- function() {
  lintr::make_linter_from_xpath(
    xpath        = "//expr[ LEFT_ASSIGN and expr[1]/SYMBOL[text() = '.onLoad' or text() = '.onAttach'] and expr[FUNCTION]/descendant::SYMBOL_FUNCTION_CALL[ text() = 'system' or text() = 'system2' ] ]",
    lint_message = "system() or system2() inside .onLoad or .onAttach hooks execute\n     arbitrary shell commands automatically when a package is loaded.",
    type         = "warning"
  )()
}
